### ISSUE TITLE
Don't stretch podcast artwork in playback 

### ISSUE THREAD

**Issue by b-aaron** [Automattic/pocket-casts-android#1660]
### Description

I have a podcast feed that has a non-square artwork image (unwilling to share publicly, I can give it to a developer privately if needed) and that gets stretched to fit a square.

Because of the design of the app, I understand this behavior to fit in with the other square images.
However in playback, the app already accepts non-square images for custom files. I would like Pocket Casts to use this behavior for podcast feeds that have such non-square artwork images. This behavior would also be good for media notification.

Additionally, I would like to bring up the discussion on whether to stretch or crop these images to fit a square

### Step-by-step reproduction instructions

1. Add Podcast feed with non-square podcast artwork
2. Notice that artwork gets stretched in all uses throughout the app (Home page, Podcast page, Playback page, Media Notification)

### Screenshots or screen recording

![podcast_page.jpg](https://github.com/Automattic/pocket-casts-android/assets/72910336/7074cfcf-112f-4374-85a0-2590607d7927)

![player.jpg](https://github.com/Automattic/pocket-casts-android/assets/72910336/9342e3cb-a652-438e-9cf3-45d010d4baf5)

![original.jpg](https://github.com/Automattic/pocket-casts-android/assets/72910336/b4fa2b29-28a4-4460-b2c1-1cdd72ea5f33)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by Mukuljangir372** [comment]
Can you post some screenshots or video for reference? Thanks

**Comment by b-aaron** [comment]
@Mukuljangir372 

> Can you post some screenshots or video for reference? Thanks

I sent them to you privately.

**Comment by Inrumpo** [comment]
On a similar note:
Version 7.54 (9180) just introduced the stretching even for square cover images. This was introduced as a feature, but feels like a bug. 
Since most podcast covers are square, they're now weirdly truncated on both sides. Slogans, graphics and other information will be cut, decreasing the overall experience.

**Comment by CookieyedCodes** [comment]
> On a similar note:
> Version 7.54 (9180) just introduced the stretching even for square cover images. This was introduced as a feature, but feels like a bug. 
> Since most podcast covers are square, they're now weirdly truncated on both sides. Slogans, graphics and other information will be cut, decreasing the overall experience.

This has allready been fixed it will be coming in RC2 😉

**Comment by tmeader** [comment]
Any word on a fix for stretched landscape artwork? I'm seeing this behavior on multiple podcasts.

**Comment by CookieyedCodes** [comment]
> Any word on a fix for stretched landscape artwork? I'm seeing this behavior on multiple podcasts.

It is fixed in rc.2

**Comment by tmeader** [comment]
No, it's not. This behavior is still happening for "widescreen" (ie - rectangular) artwork with RC2. Images attached. These showed the full widescreen image properly prior to the two latest RCs. The problem with square artwork being "zoomed in" and cropped on the sides was fixed, not this issue. I'm currently running RC2 (9184).

![Screenshot_20240118-171148](https://github.com/Automattic/pocket-casts-android/assets/26943453/654a6953-58bd-481a-b971-096b0b5d3506)
![Screenshot_20240118-171159](https://github.com/Automattic/pocket-casts-android/assets/26943453/602297c8-2c1f-4081-9d37-bd279435df77)

**Comment by CookieyedCodes** [comment]
> No, it's not. This behavior is still happening for "widescreen" (ie - rectangular) artwork with RC2. Images attached. These showed the full widescreen image properly prior to the two latest RCs. The problem with square artwork being "zoomed in" and cropped on the sides was fixed, not this issue. I'm currently running RC2 (9184).
> 
> ![Screenshot_20240118-171148](https://github.com/Automattic/pocket-casts-android/assets/26943453/654a6953-58bd-481a-b971-096b0b5d3506)
> ![Screenshot_20240118-171159](https://github.com/Automattic/pocket-casts-android/assets/26943453/602297c8-2c1f-4081-9d37-bd279435df77)
> 

Ah fair enough, got to love aspect ratios XD
@ashiagr

**Comment by MiSikora** [comment]
Thanks for reporting! Closing in favor of #1719 as it contains easier reproduction steps and some technical details with a possible solution.

**Comment by b-aaron** [comment]
> Thanks for reporting! Closing in favor of #1719 as it contains easier reproduction steps and some technical details with a possible solution.

Honestly, I don't feel like this is the same issue at all, since here, the issue is in the podcast **feed's** image being _stretched_, rather than a podcast **episode's** image being _cropped_.

Unfortunately, I can't check, whether your fix mentioned in the other issue also fixes this issue.
And, as it is a podcast feed which I am unwilling to share publicly, I unfortunately do not have any example feed that I could share with you.

I will gladly come back to this, once a fix to the other issue gets released, to comment on whether this issue got fixed.

**Comment by MiSikora** [comment]
Sorry @b-aaron, I've got confused by the other comment piggybacking on this issue and assuming that's what it is about. It's a bit hard for me to understand this issue without reproduction steps and/or screenshots linked to the issue.

**Comment by CookieyedCodes** [comment]
@MiSikora use a service like listenbox and you'll be able to understand what's happening 🤔 😉, its seeming that landscape files are now getting zoomed to match the top to bottom ratio, where previously it kept it landscape instead of fitting it in the square, not sure I'm explaining it well tho 😅

**Comment by b-aaron** [comment]
@MiSikora Understandable, no problem.
Here are some cropped screenshots along with the original feed image.

To clarify my intent for this issue once again, I am only asking for the feed image to show up normally in the player. I know that a non-square podcast feed image would bring a lot more issues, which would be too much of an effort to change for such limited usecase.

![podcast_page.jpg](https://github.com/Automattic/pocket-casts-android/assets/72910336/7074cfcf-112f-4374-85a0-2590607d7927)

![player.jpg](https://github.com/Automattic/pocket-casts-android/assets/72910336/9342e3cb-a652-438e-9cf3-45d010d4baf5)

![original.jpg](https://github.com/Automattic/pocket-casts-android/assets/72910336/b4fa2b29-28a4-4460-b2c1-1cdd72ea5f33)

**Comment by MiSikora** [comment]
> its seeming that landscape files are now getting zoomed to match the top to bottom ratio, where previously it kept it landscape instead of fitting it in the square, not sure I'm explaining it well tho

@CookieyedCodes Yes, I think this is the issue I reported in #1719.

@b-aaron I was able to reproduce the issue using the podcast (I searched for anything related to Pratchett). However, it looks like that the squished/stretched image is provided like this in the podcast data. There are two images - JPEG and WebP. JPEG looks normally, it is squared and cropped to the center. WebP is squared and distorted. I assume that Android app uses the second one. TBH I don't know how those images are set in our database. I'll ask about it internally tomorrow and come back to you when I have an aswer.

**Comment by b-aaron** [comment]
@MiSikora Thanks for looking into it. Since you seem to have found it, I sent the link to the feed via mail, to make sure we're really talking about the same one.

**Comment by CookieyedCodes** [comment]
Webp was added a few months ago to cut down on storage size but we'll done finding it 😉

**Comment by MiSikora** [comment]
@b-aaron Ok, so this is an issue with how we process artworks on the server side. We need to fix it there. I don't know when I'll find time for this particular problem but I'll try to prioritize it next week.

**Comment by MiSikora** [comment]
The fix is now deployed to the backend. We'd need to run an automattic job to update all podcast images. However, I updated the podcast in this issue manually. It should be reflected in the app soon.
