### ISSUE TITLE
On the Podcast details screen, the last podcast is blocked by the now playing element

### ISSUE THREAD

**Issue by Capable-Tea-001** [Automattic/pocket-casts-android#4164]
### Description

As title

![Image](https://github.com/user-attachments/assets/b11ef47d-c413-41bf-98e3-5f1919b147a0)

### Step-by-step reproduction instructions

Go to a podcast with more than ~10 episodes, scroll to the bottom.

Cannot see the bottom episode. 

### Screenshots or screen recording

![Image](https://github.com/user-attachments/assets/2fe67c7b-a9ea-4d6e-8fa9-f55bb253d9db) 

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 8
Android 16
Version 7.92-rc-3 (9350)

**Comment by geekygecko** [comment]
Thanks for reporting this issue. I haven’t been able to reproduce it yet. Could you try restarting the app to see if the issue persists? Hopefully, we can work out how to get the app into this state, it will make it easier to fix.

**Comment by Capable-Tea-001** [comment]
Rebooted my phone and it's still an issue 

![Image](https://github.com/user-attachments/assets/d816adb8-db13-4051-a16b-0e7f1c105be9)

![Image](https://github.com/user-attachments/assets/1445f2f0-65bf-4e2e-9824-b8cd827ba954)

**Comment by FlashGooden** [comment]
> Thanks for reporting this issue. I haven’t been able to reproduce it yet. Could you try restarting the app to see if the issue persists? Hopefully, we can work out how to get the app into this state, it will make it easier to fix.

Hey @geekygecko, I think I found out what issue the client was seeing. In order to reproduce, archive all the shows in a list then show/unhide the archived list. It looks like at the bottom of that list will block the last podcast seen, but only on first scroll?? When the screen times out, on waking and scrolling again you can see the last podcast. I used the "Sanctuary" podcast as a reference, I am using Android 15 on a Galaxy Z Fold 6 in portrait mode.

**Comment by Capable-Tea-001** [comment]
FYI, I cannot reproduce on Version 7.96-rc-1 (9365)

**Comment by FlashGooden** [comment]
Ah ok. I'm seeing it on 7.95 (9364). Maybe it's fixed in a later release.

**Comment by Capable-Tea-001** [comment]
Tell a lie... Still occurring: 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/e92f0848-2e9c-4f05-872e-f1e8317a1062" />

**Comment by Capable-Tea-001** [comment]
Having switched to the browser to add the comment and screenshot, switching back to PC then resolves the issue: 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/8bc96a1c-b481-4aa9-8c9c-fc292cb9e8e4" />
